### ISSUE TITLE
Master version

### ISSUE THREAD

**Issue by tiagoicp** [ZenVoich/mocv#4]
Hi ZenVoich,

Today came across your version manager, pretty good.

Can't stop being impressed with your good work.

I now will need to pull the latest version (master) of motoko. For development purposes.

There isn't any easy way yet to get it right?

Maybe it would be a good feature to add, would you consider?

Thanks, 
Tiago

**Comment by ZenVoich** [comment]
Hi Tiago 

I think this will be a rare case. Also it will be necessary to implement completely different logic - to pull the repository and build it all locally.

Unfortunately, I don’t think this feature will be implemented.

I'm working on integrating mocv into mops with per-project moc version management. So eventually mocv will be abandoned.

**Comment by tiagoicp** [comment]
Hi ZenVoich,

Yes, I now understand. Also you would need to compile to different operating systems. It would be too much work for little usage. 

When I proposed I thought it was an easy addition, but now see it is not.

Thanks for the fast reply, will close now.
